---
- name: reload systemd
  systemd:
    daemon_reload: true

- name: restart compose services
  systemd:
    name: docker-compose-srv
    state: restarted

- name: restart pihole dns
  command: docker exec pihole pihole restartdns
  changed_when: true
